---
namespace: "{{ lookup('env','NAMESPACE') | default('lastop-cem-demo-apb', true) }}"
terminationMessagePathFile: "{{ lookup('env','TERMINATIONMSGPATHFILE') | default('/dev/termination-log', true) }}"
