- name: lastop-cem-demo-apb deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: deprovision-lastop-cem-demo-apb
    playbook_debug: false
